### ISSUE TITLE
Добавить описание проекта в readme.md

### ISSUE THREAD

**Issue by makometr** [BaatleTeam/Tetris#1]
### В файле readme должна содержаться информация:
- название проекта, используемые библиотеки и их версии, языки проекта (один, лол)
- принятый участниками порядок внесения изменений в кодовую базу (подробная инструкция по работе с репо)
- спецификация приложения вместе с ТЗ (можно в отдельный файл)

### Договориться о:
- работе с ветками в репо
- создании issues
- стиле кодирования
- фичи конечного приложения (что должны получить в итоге)

**Comment by Denmey** [comment]
Examples:
https://gist.github.com/PurpleBooth/109311bb0361f32d87a2
https://github.com/SFML/SFML/blob/master/readme.md
https://www.sfml-dev.org/contribute.php
https://www.sfml-dev.org/style.php
https://google.github.io/styleguide/cppguide.html
https://lebkowski.name/git-workflow/

**Comment by Denmey** [comment]
@makometr What do you mean by specification?
Created a branch for updating readme.md, feel free to push commits to it. See PR #4

**Comment by makometr** [comment]
![image](https://user-images.githubusercontent.com/21985069/43830971-5c15841a-9b0b-11e8-97cf-1f31f82b2971.png)

**Comment by makometr** [comment]
closed by #4
